source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.2'

group :jekyll_plugins do
  gem 'jekyll-theme-cayman', '~> 0.2.0'
end

# This is needed because of a bug in Jekyll:
# https://github.com/jekyll/jekyll/issues/8523
gem 'webrick'
