name: MacOS
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "misc/site/**" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  OPENCV_VERSION: "4.6.0"

jobs:
  build-macos-12:
    runs-on: macos-12
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install prerequisites
      run: |
        brew install sdl2 spdlog catch2

    - name: Cache OpenCV
      uses: actions/cache@v3
      id: cache-opencv
      with:
        path: opencv/install
        key: ${{runner.os}}-opencv-${{env.OPENCV_VERSION}}-${{hashFiles('misc/build/opencv_minimal_flags.txt')}}

    - name: Install OpenCV
      if: steps.cache-opencv.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/opencv/opencv.git --depth 1 --branch $OPENCV_VERSION
        cd opencv
        cmake -B build \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_INSTALL_PREFIX=install \
          `cat ../misc/build/opencv_minimal_flags.txt`
        cmake --build build --target install -j $(nproc)
        cd ..

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_INSTALL_PREFIX=install \
          -DBUILD_TESTING=ON \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DOpenCV_DIR=opencv/install/lib/cmake/opencv4

    - name: Build
      run: cmake --build build -j $(nproc) --target install

    - name: Run Tests
      run: |
        cd build
        ctest
        cd ..
